export { authService } from "./auth";
export type { AuthUser, AuthResponse, LoginInput, SignupInput } from "./auth";
export { profileService } from "./profile";
export type { UserProfile } from "./profile";
export { notesService } from "./notes";
export type { Note } from "./notes";
export { flashcardsService } from "./flashcards";
export type { FlashcardDeck, Flashcard } from "./flashcards";
export { quizzesService } from "./quizzes";
export type { Quiz, QuizQuestion, QuizAttempt } from "./quizzes";
export { plannerService } from "./planner";
export type { PlannerEvent } from "./planner";
export { dashboardService } from "./dashboard";
export type { DashboardStats } from "./dashboard";
export { notificationsService } from "./notifications";
export type { Notification } from "./notifications";
export { chatService } from "./chat";
export type { ChatConversation, ChatMessage } from "./chat";
export { uploadsService } from "./uploads";
export type { UploadedFile } from "./uploads";