/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppWeakTopicsRouteImport } from './routes/app.weak-topics'
import { Route as AppVoiceRouteImport } from './routes/app.voice'
import { Route as AppSummariesRouteImport } from './routes/app.summaries'
import { Route as AppQuizzesRouteImport } from './routes/app.quizzes'
import { Route as AppPredictorRouteImport } from './routes/app.predictor'
import { Route as AppPlannerRouteImport } from './routes/app.planner'
import { Route as AppFlashcardsRouteImport } from './routes/app.flashcards'
import { Route as AppDocumentsRouteImport } from './routes/app.documents'
import { Route as AppChatRouteImport } from './routes/app.chat'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWeakTopicsRoute = AppWeakTopicsRouteImport.update({
  id: '/weak-topics',
  path: '/weak-topics',
  getParentRoute: () => AppRoute,
} as any)
const AppVoiceRoute = AppVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => AppRoute,
} as any)
const AppSummariesRoute = AppSummariesRouteImport.update({
  id: '/summaries',
  path: '/summaries',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizzesRoute = AppQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => AppRoute,
} as any)
const AppPredictorRoute = AppPredictorRouteImport.update({
  id: '/predictor',
  path: '/predictor',
  getParentRoute: () => AppRoute,
} as any)
const AppPlannerRoute = AppPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AppRoute,
} as any)
const AppFlashcardsRoute = AppFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/chat': typeof AppChatRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/flashcards': typeof AppFlashcardsRoute
  '/app/planner': typeof AppPlannerRoute
  '/app/predictor': typeof AppPredictorRoute
  '/app/quizzes': typeof AppQuizzesRoute
  '/app/summaries': typeof AppSummariesRoute
  '/app/voice': typeof AppVoiceRoute
  '/app/weak-topics': typeof AppWeakTopicsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/chat': typeof AppChatRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/flashcards': typeof AppFlashcardsRoute
  '/app/planner': typeof AppPlannerRoute
  '/app/predictor': typeof AppPredictorRoute
  '/app/quizzes': typeof AppQuizzesRoute
  '/app/summaries': typeof AppSummariesRoute
  '/app/voice': typeof AppVoiceRoute
  '/app/weak-topics': typeof AppWeakTopicsRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/chat': typeof AppChatRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/flashcards': typeof AppFlashcardsRoute
  '/app/planner': typeof AppPlannerRoute
  '/app/predictor': typeof AppPredictorRoute
  '/app/quizzes': typeof AppQuizzesRoute
  '/app/summaries': typeof AppSummariesRoute
  '/app/voice': typeof AppVoiceRoute
  '/app/weak-topics': typeof AppWeakTopicsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/app/chat'
    | '/app/documents'
    | '/app/flashcards'
    | '/app/planner'
    | '/app/predictor'
    | '/app/quizzes'
    | '/app/summaries'
    | '/app/voice'
    | '/app/weak-topics'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/app/chat'
    | '/app/documents'
    | '/app/flashcards'
    | '/app/planner'
    | '/app/predictor'
    | '/app/quizzes'
    | '/app/summaries'
    | '/app/voice'
    | '/app/weak-topics'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/app/chat'
    | '/app/documents'
    | '/app/flashcards'
    | '/app/planner'
    | '/app/predictor'
    | '/app/quizzes'
    | '/app/summaries'
    | '/app/voice'
    | '/app/weak-topics'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/weak-topics': {
      id: '/app/weak-topics'
      path: '/weak-topics'
      fullPath: '/app/weak-topics'
      preLoaderRoute: typeof AppWeakTopicsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/voice': {
      id: '/app/voice'
      path: '/voice'
      fullPath: '/app/voice'
      preLoaderRoute: typeof AppVoiceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/summaries': {
      id: '/app/summaries'
      path: '/summaries'
      fullPath: '/app/summaries'
      preLoaderRoute: typeof AppSummariesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quizzes': {
      id: '/app/quizzes'
      path: '/quizzes'
      fullPath: '/app/quizzes'
      preLoaderRoute: typeof AppQuizzesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/predictor': {
      id: '/app/predictor'
      path: '/predictor'
      fullPath: '/app/predictor'
      preLoaderRoute: typeof AppPredictorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/planner': {
      id: '/app/planner'
      path: '/planner'
      fullPath: '/app/planner'
      preLoaderRoute: typeof AppPlannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/flashcards': {
      id: '/app/flashcards'
      path: '/flashcards'
      fullPath: '/app/flashcards'
      preLoaderRoute: typeof AppFlashcardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppFlashcardsRoute: typeof AppFlashcardsRoute
  AppPlannerRoute: typeof AppPlannerRoute
  AppPredictorRoute: typeof AppPredictorRoute
  AppQuizzesRoute: typeof AppQuizzesRoute
  AppSummariesRoute: typeof AppSummariesRoute
  AppVoiceRoute: typeof AppVoiceRoute
  AppWeakTopicsRoute: typeof AppWeakTopicsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppFlashcardsRoute: AppFlashcardsRoute,
  AppPlannerRoute: AppPlannerRoute,
  AppPredictorRoute: AppPredictorRoute,
  AppQuizzesRoute: AppQuizzesRoute,
  AppSummariesRoute: AppSummariesRoute,
  AppVoiceRoute: AppVoiceRoute,
  AppWeakTopicsRoute: AppWeakTopicsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
